package one.digitalinnovation.web.herosapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Heroes_Table")
public class Heroes {


    @DynamoDBHashKey(attributeName = "heroId")
    @DynamoDBAutoGeneratedKey
    private String heroId;


    @DynamoDBAttribute(attributeName = "heroName")
    private String heroName;


    @DynamoDBAttribute(attributeName = "heroUniverse")
    private String heroUniverse;


    @DynamoDBAttribute(attributeName = "heroFilms")
    private String heroFilms;

    public Heroes(Heroes hero) {
        this.heroName = hero.getHeroName();
        this.heroUniverse = hero.getHeroUniverse();
        this.heroFilms = hero.getHeroFilms();
    }
}
